### ISSUE TITLE
What would we do if key is not found?

### ISSUE THREAD

**Issue by eduardostalinho** [Onyo/jsonbender#4]
I found a thing that can be discussed in the scope of this project.

When jsonbender can't find a key, it raises an error.
But I'm working with jsonbender with a list of dicts that can have a key or not.
Could we work with it using the `F()` Selector? Or can we pass a kwarg to `bend()` function like `silent=True` to pass the bending of this object? Or a kwarg to bend() that says to evaluate a not found key to None?

**Comment by etandel** [comment]
Passing a key to `bend()` is tricky because you wouldn't be able to have both required and optional keys: either all would be optional or all would be required. I was thinking in maybe creating a `OptionalS` selector that takes a default value:
```
{
    "key": OptionalS('optional', 'tree', default="not found")
}
```
What do you think, @eduardostalinho?

**Comment by eduardostalinho** [comment]
It's a good way. But what would be the difference from this to implement the `default` keywarh to the `S` selector?

Trynig to answer this same question. Woul it be a difference on the selectors implementation?

**Comment by etandel** [comment]
It could just as well be a `default` kwarg on the `S` selector which when present would make it optional. However, a case with a lot of `default=None` would make the mapping somewhat cumbersome; the separate selector would make it possible to have a default value (`None`) to the `default` kwarg. Also, a different selector makes it easier for grepping and keeps the implementation simpler.

BTW, an interesting related feature would be for the optional selector to stop the composition chain, sou that later selectors wouldn't need to to worry about `None` etc., somewhat like `Maybe` in Haskell or `Optional` in Scala.

**Comment by eduardostalinho** [comment]
I see that the implementation would be very different. I'm making some exeperiments taking you comment in consideration.
